### ISSUE TITLE
Adding JAR dependency

### ISSUE THREAD

**Issue by chrischin478** [alrouen/local-aws-glue-v3-zeppelin#1]
How can a JAR dependency be included? Should it just be added to the Glue job that's used for export?

**Comment by alrouen** [comment]
Hi,

If you are speaking about including jars in your zeppelin notebook,  you check my example with delta.io jars in this repository : 

- First include a jar package dependencies in the zeppelin spark interpreter (for this project I did it manually in the zeppelin interface and save the json config file for docker image (https://github.com/alrouen/local-aws-glue-v3-zeppelin/blob/main/docker/interpreter-0.10.0.json)
- Then in your notebook you need to load the jar file with pyspark spark context object : https://github.com/alrouen/local-aws-glue-v3-zeppelin/blob/eb89430eb59928f347178557510d5271a3300c81/delta/delta-sample.py#L38

But if you want to load the same jar in a Glue job (deployed in AWS) the process is a little bit different : 

- You need to specify all jar dependencies in the job details, and you need to store the jars in a s3 bucket available by your job role (as explained here: https://github.com/alrouen/local-aws-glue-v3-zeppelin/blob/eb89430eb59928f347178557510d5271a3300c81/delta/delta-sample.py#L23)
- Then for your job, the process is the same, you need to use the pyspark spark context to load the jar

Did I answered to your question ?

**Comment by chrischin478** [comment]
I'm referring to jars in the notebook. I'll try to follow your instructions this weekend. Thanks for the prompt response.

**Comment by chrischin478** [comment]
I'm getting an error at docker build step 4/29. Any idea why?

```
Step 4/29 : RUN curl -SsL https://aws-glue-etl-artifacts.s3.amazonaws.com/glue-3.0/spark-3.1.1-amzn-0-bin-3.2.1-amzn-3.tgz | tar -C /opt --warning=no-unknown-keyword -xzf -
 ---> Running in 42787b554d97

gzip: stdin: not in gzip format
tar: Child died with signal 13
tar: Error is not recoverable: exiting now
curl: (23) Failure writing output to destination
The command '/bin/sh -c curl -SsL https://aws-glue-etl-artifacts.s3.amazonaws.com/glue-3.0/spark-3.1.1-amzn-0-bin-3.2.1-amzn-3.tgz | tar -C /opt --warning=no-unknown-keyword -xzf -' returned a non-zero code: 2
```

**Comment by chrischin478** [comment]
Ah, that tgz file is an uncompressed POSIX tar. I'll try taking the `z` option out of the tar command.

Edit: that worked

**Comment by chrischin478** [comment]
I don't see any reference to `io.delta_delta-core_2.12-1.0.0.jar` in the json config or docker file. I would think that the .jar file needs to be added to the Docker image. Are you saying that similiar to [**this** ](https://zeppelin.apache.org/docs/0.6.0/manual/dependencymanagement.html), you're adding the .jar file as an artifact? If so, wouldn't the jar file need to be local to the docker image?

**Comment by alrouen** [comment]
In the zeppelin config file it's here : https://github.com/alrouen/local-aws-glue-v3-zeppelin/blob/eb89430eb59928f347178557510d5271a3300c81/docker/interpreter-0.10.0.json#L1069 

In the dockerfile, I do not add any reference to jar files, as this is a zeppelin configuration (interpreter.json file) or a AWS Glue configuration (when deploying the job)

**Comment by chrischin478** [comment]
Is this docker image capable of using the Glue catalog as the Hive metastore?

**Comment by alrouen** [comment]
Yes, just use the Glue context for that ( glueContext.create_dynamic_frame.from_catalog(...) )

**Comment by chrischin478** [comment]
When running the docker build command the container immediately exits with status `Exited (127)` but there's no output from command `docker logs gluedev`. Any idea what's going on? Code 127 apparently means "supplied command cannot be found" but I ssh'd into the container and the script is definitely in the CMD location defined in the Dockerfile.

**Edit**: I'm able to run the container fine on my Dell laptop with Ubuntu 20.04. The exit error code was happening on a Raspberry Pi 4 with Ubuntu 20.10. Must be either an OS or architecture compatibility issue.

**Comment by alrouen** [comment]
Ok, seems to be good ?
