### ISSUE TITLE
Jupyter support

### ISSUE THREAD

**Issue by archenroot** [alrouen/local-aws-glue-v3-zeppelin#2]
Hi, thx for this glue docker file. Would you be so kind to suggest how to support jupyter instead of zeppelin? Thx

**Comment by alrouen** [comment]
Hi, 

It is something interesting indeed but could require a bit of work in the docker image. 
It require to install Jupyter lab inside the docker image and make it work with the spark/pyspark environment.

Unfortunately, I don't have the time for that at the moment. Will have a look in early 2022

Thanks !

**Comment by EzuA** [comment]
Hi,

I have made some modifications to the dockerfile using `jupyter/scipy-notebook` image and I have a working version. If you want, I can contribute with the jupyter notebook support.

**Comment by alrouen** [comment]
Yes please !

**Comment by archenroot** [comment]
Also in meanwhile, I received infor from AWS team: https://github.com/awslabs/aws-glue-libs/issues/96#issuecomment-992617239

its related to glue v3 support from AWS in general.

**Comment by archenroot** [comment]
@EzuA - can you post your notes or full dockerfile for jupyter integration, so we can have eventually all integrated dockerfile covering all requirements.

**Comment by EzuA** [comment]
Sure, I am going to create a new branch with the dockerfile in other folder.

**Comment by archenroot** [comment]
Actually as soon as I would like to integrate minio s3 and also AWS MWAA local docker runner I think I will use this repo dockerfile to extend it can be started in following modes:
- local with jupyter (which @EzuA introduce on branch)
- local with zeppeling which is default in this repo
- start master - in such case starting image with jupyter must configure master spark://otherhost:7077
- start worker - similar here to let worker connect to master
Sto that way I can have complete AWS Spark local cluster with local s3 storage available.

Still, one remaining thing is to test how AWS MWAA local runner will invoke Glue job in docker, should I use Glue operator or Spark only, ie. I will need Airflow DAG to determine if running local or AWS to use proper operator dynamically, but I think its quite possible as soon as DAG is nothing more then Python script.

Thx a lot again for this repo.

The idea to support this is to let default entry point in form of a bash script and use CMD to pass the following variables:
- jupyter-local
- zeppelin-local

And I will try to add the following combinations:
- master - spin up master spark node
- worker - spin up worker spark node
- jupyter-master - jupyter configured via spark-defaults.conf to remote master
- same for zeppelin
- jupyter-master-minios3 - will configure core-site.xml content to use s3a implementation, but mostly to connect to local-minios3 host which will be expected to run in other docker instance (eg. s3 endpoint_url parameter)
That is the idea for this weekend.
Any comments are welcomed to keep it still generic but provide parametrized runtimes...
