### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by acpn** [alrouen/local-aws-glue-v3-zeppelin#3]
I'm getting this error when run a sed command at line 39.

`[10/19] RUN sed -i 's/spark.master jes/spark.master local/g' /opt/amazon/conf/spark-defaults.conf:
#14 0.224 sed: can't read /opt/amazon/conf/spark-defaults.conf: No such file or directory
------
executor failed running [/bin/sh -c sed -i 's/spark.master jes/spark.master local/g' /opt/amazon/conf/spark-defaults.conf]: exit code: 2`

Any thoughts?

Great work btw on putting all this together.

**Comment by alrouen** [comment]
this spark-defaults.conf file is coming from the archive you need to collect from AWS Glue. 
Have you run the job to build this archive ? Did you checked this file exists in the archive ?

**Comment by acpn** [comment]
Thanks, I figure out the spark-defaults.conf file stays at /glue3-opt-amazon/conf/spark-defaults.conf. Thank you for all your work on this, is a great start point for what i need :)
