### ISSUE TITLE
Link to glue3.zip

### ISSUE THREAD

**Issue by chiragrajk** [alrouen/local-aws-glue-v3-zeppelin#5]
> - From the S3 bucket, download the glue3.zip file

Where can I find the link to download `glue3.zip` file as mentioned in the README file.

**Comment by archenroot** [comment]
you need to run the aws-glue-export-job.py directly on AWS Glue.

What it does:
zipfolder('/tmp/glue3.zip', '/opt/amazon')
upload_file('/tmp/glue3.zip', TARGET_BUCKET)

So inside this /opt/amazon folder is actually amazon version of Spark distribution enhanced by Glue libraries. To make this dockerfile working you need to run it first.

But there is also AWS Glue Lib repository where you can get the jars and python lib and also you can download amazon spark distro and constuct it other way.

**Comment by chiragrajk** [comment]
Thanks!
